# Generated by Django 3.0.5 on 2022-03-01 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('C', 'CoEd')], max_length=1)),
                ('registered', models.BooleanField(default=False)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField()),
                ('street_address', models.CharField(max_length=500)),
                ('lat', models.CharField(max_length=50)),
                ('log', models.CharField(max_length=50)),
                ('one_seater_room', models.IntegerField()),
                ('one_seater_price', models.IntegerField()),
                ('two_seater_room', models.IntegerField()),
                ('two_seater_price', models.IntegerField()),
                ('three_seater_room', models.IntegerField()),
                ('three_seater_price', models.IntegerField()),
                ('attached_bathrooms', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('pets_friendly', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('water_heating', models.BooleanField(default=False)),
                ('linens', models.BooleanField(default=False)),
                ('iron', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('watercooler', models.BooleanField(default=False)),
                ('security_cameras', models.BooleanField(default=False)),
                ('mess', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('total_area', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hostel_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Hostel_images')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostels_app.Hostel')),
            ],
        ),
    ]
