# Generated by Django 3.0.5 on 2022-03-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels_app', '0002_hostel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='registered',
        ),
        migrations.AddField(
            model_name='hostel',
            name='type',
            field=models.CharField(choices=[('RB', 'I am a registered business'), ('PB', 'I am a private seller')], default='PB', max_length=2),
            preserve_default=False,
        ),
    ]
