# Generated by Django 3.0.5 on 2022-03-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels_app', '0003_auto_20220301_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_images',
            name='image',
            field=models.FileField(upload_to='Hostel_images'),
        ),
    ]
