# Generated by Django 3.0.5 on 2022-03-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels_app', '0004_auto_20220301_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='type',
            field=models.CharField(choices=[('RB', 'I am a registered business'), ('PB', 'I am a private seller')], default='RB', max_length=2),
        ),
    ]
