# Generated by Django 3.0.5 on 2022-03-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels_app', '0005_auto_20220301_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='lat',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='log',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='one_seater_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='one_seater_room',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='three_seater_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='three_seater_room',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='two_seater_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='two_seater_room',
            field=models.IntegerField(default=0),
        ),
    ]
