# Generated by Django 3.0.5 on 2022-03-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels_app', '0009_hostelreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
