# Generated by Django 3.0.5 on 2022-03-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels_app', '0011_auto_20220303_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelreview',
            name='locality_rate',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
