# Generated by Django 3.0.5 on 2022-03-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels_app', '0013_auto_20220303_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelreview',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hostelreview',
            name='name',
        ),
    ]
