# Generated by Django 3.0.5 on 2022-03-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels_app', '0016_auto_20220303_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='hostels',
            field=models.ManyToManyField(null=True, to='Hostels_app.Hostel'),
        ),
    ]
