# Generated by Django 3.0.5 on 2022-03-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels_app', '0017_auto_20220308_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='sentiment',
            field=models.IntegerField(null=True),
        ),
    ]
