# Generated by Django 3.0.5 on 2022-03-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels_app', '0018_hostel_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='sentiment',
            field=models.FloatField(null=True),
        ),
    ]
