# Generated by Django 3.0.5 on 2022-03-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels_app', '0019_auto_20220308_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='timestamp',
        ),
    ]
