# Generated by Django 3.0.5 on 2022-03-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels_app', '0020_remove_hostel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='log',
            field=models.FloatField(null=True),
        ),
    ]
