# Generated by Django 3.0.5 on 2022-03-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels_app', '0022_auto_20220310_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='boys',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='girls',
            field=models.BooleanField(default=False),
        ),
    ]
