# Generated by Django 3.0.5 on 2022-03-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels_app', '0023_auto_20220310_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='log',
            field=models.FloatField(null=True),
        ),
    ]
