# Generated by Django 3.0.5 on 2022-03-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels_app', '0024_hostel_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='hostels',
            field=models.ManyToManyField(to='Hostels_app.Hostel'),
        ),
    ]
